apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bot-app
  name: bot-app
spec:
  containers:
    - args:
        - tail
        - -F
        - anything
      image: cfmanteiga/alpine-bash-curl-jq
      name: bot-app
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /tmp/program.sh
          name: bot-app-cm0
          subPath: program.sh
  restartPolicy: OnFailure
  volumes:
    - configMap:
        items:
          - key: program.sh
            path: program.sh
        name: bot-app-cm0
      name: bot-app-cm0
