apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: client
    spec:
      containers:
        - args:
            - infinity
          command:
            - sleep
          image: cyberark/conjur-cli:8
          name: conjur-client
          volumeMounts:
            - mountPath: /policy
              name: client-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: client-cm0
          name: client-cm0
