apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: conjur
  name: conjur
spec:
  containers:
    - args:
        - server
      env:
        - name: CONJUR_TELEMETRY_ENABLED
          value: "false"
        - name: DATABASE_URL
          value: postgres://postgres:SuperSecretPg@database/postgres
      image: cyberark/conjur
      name: conjur-server
      ports:
        - containerPort: 80
          protocol: TCP
  restartPolicy: OnFailure
