apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: password
            - name: POSTGRES_PASSWORD
              value: SuperSecretPg
          image: postgres:15
          name: postgres-database
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
