apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  containers:
    - image: nginx:latest
      name: nginx-proxy
      ports:
        - containerPort: 443
          protocol: TCP
      volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: proxy-cm0
          readOnly: true
        - mountPath: /etc/nginx/tls
          name: proxy-cm1
          readOnly: true
  restartPolicy: OnFailure
  volumes:
    - configMap:
        name: proxy-cm0
      name: proxy-cm0
    - configMap:
        name: proxy-cm1
      name: proxy-cm1
